package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"time"
)

const versionTemplate = `// Code generated by go generate; DO NOT EDIT.

package version

// Version information
var (
	Version   = "{{.Version}}"
	CommitSHA = "{{.CommitSHA}}"
	BuildDate = "{{.BuildDate}}"
	BuildInfo = "{{.BuildInfo}}"
)

// GetVersion returns the full version string
func GetVersion() string {
	if CommitSHA != "" {
		return Version + "+" + CommitSHA[:7]
	}
	return Version
}

// GetFullVersion returns version with build info
func GetFullVersion() string {
	version := GetVersion()
	info := ""
	if BuildDate != "" {
		info = BuildDate
	}
	if BuildInfo != "" {
		if info != "" {
			info += ", " + BuildInfo
		} else {
			info = BuildInfo
		}
	}
	if info != "" {
		return version + " (" + info + ")"
	}
	return version
}
`

type VersionData struct {
	Version   string
	CommitSHA string
	BuildDate string
	BuildInfo string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	// Find the project root (where VERSION file is)
	projectRoot, err := findProjectRoot()
	if err != nil {
		return fmt.Errorf("failed to find project root: %w", err)
	}

	// Read version from VERSION file
	versionFile := filepath.Join(projectRoot, "VERSION")
	versionBytes, err := os.ReadFile(versionFile)
	if err != nil {
		return fmt.Errorf("failed to read VERSION file: %w", err)
	}

	version := strings.TrimSpace(string(versionBytes))
	// Remove comments and get just the version number
	for _, line := range strings.Split(version, "\n") {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "#") {
			version = line
			break
		}
	}

	// Get git commit SHA
	commitSHA, err := getGitCommitSHA(projectRoot)
	if err != nil {
		// If we can't get git info, that's okay - we'll just use the version
		commitSHA = ""
	}

	// Get build date
	buildDate := getBuildDate()

	// Get build info (dirty state)
	buildInfo := ""
	if isDirty, _ := isGitDirty(projectRoot); isDirty {
		buildInfo = "dirty"
	}

	// Generate version file
	data := VersionData{
		Version:   version,
		CommitSHA: commitSHA,
		BuildDate: buildDate,
		BuildInfo: buildInfo,
	}

	tmpl, err := template.New("version").Parse(versionTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	outputPath := filepath.Join(projectRoot, "src", "version", "version.go")
	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	fmt.Printf("Generated version.go: %s (commit: %s)\n", version, commitSHA[:min(7, len(commitSHA))])
	return nil
}

func findProjectRoot() (string, error) {
	// Start from current directory and walk up until we find VERSION file
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		versionFile := filepath.Join(dir, "VERSION")
		if _, err := os.Stat(versionFile); err == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("VERSION file not found")
		}
		dir = parent
	}
}

func getGitCommitSHA(dir string) (string, error) {
	cmd := exec.Command("git", "rev-parse", "HEAD")
	cmd.Dir = dir
	output, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(output)), nil
}

func isGitDirty(dir string) (bool, error) {
	cmd := exec.Command("git", "status", "--porcelain")
	cmd.Dir = dir
	output, err := cmd.Output()
	if err != nil {
		return false, err
	}
	return len(strings.TrimSpace(string(output))) > 0, nil
}

func getBuildDate() string {
	// Return current date/time in RFC3339 format
	return time.Now().UTC().Format(time.RFC3339)
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
