package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	projectRoot, err := findProjectRoot()
	if err != nil {
		return fmt.Errorf("failed to find project root: %w", err)
	}

	versionBytes, err := os.ReadFile(filepath.Join(projectRoot, "VERSION"))
	if err != nil {
		return fmt.Errorf("failed to read VERSION file: %w", err)
	}

	// skip comments, grab first non-empty line
	version := ""
	for _, line := range strings.Split(string(versionBytes), "\n") {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "#") {
			version = line
			break
		}
	}

	commitSHA, err := getGitCommitSHA(projectRoot)
	if err != nil {
		commitSHA = ""
	}

	buildDate := time.Now().UTC().Format(time.RFC3339)

	buildInfo := ""
	if isDirty, _ := isGitDirty(projectRoot); isDirty {
		buildInfo = "dirty"
	}

	content := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.

package version

var (
	Version   = %q
	CommitSHA = %q
	BuildDate = %q
	BuildInfo = %q
)
`, version, commitSHA, buildDate, buildInfo)

	outputPath := filepath.Join(projectRoot, "src", "version", "version.go")
	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write version.go: %w", err)
	}

	fmt.Printf("Generated version.go: %s (commit: %s)\n", version, commitSHA[:min(7, len(commitSHA))])
	return nil
}

func findProjectRoot() (string, error) {
	// Start from current directory and walk up until we find VERSION file
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		versionFile := filepath.Join(dir, "VERSION")
		if info, err := os.Stat(versionFile); err == nil && !info.IsDir() {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("VERSION file not found")
		}
		dir = parent
	}
}

func getGitCommitSHA(dir string) (string, error) {
	cmd := exec.Command("git", "rev-parse", "HEAD")
	cmd.Dir = dir
	output, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(output)), nil
}

func isGitDirty(dir string) (bool, error) {
	cmd := exec.Command("git", "status", "--porcelain")
	cmd.Dir = dir
	output, err := cmd.Output()
	if err != nil {
		return false, err
	}
	return len(strings.TrimSpace(string(output))) > 0, nil
}
