// Code generated by go generate; DO NOT EDIT.

package completions

// CompletionTemplates contains the embedded shell completion scripts
var CompletionTemplates = map[string]string{
	"bash": `# Bash completion for gitgum (template - __GITGUM_CMD__ will be replaced)

_gitgum_completion() {
    local cur prev words cword
    _init_completion || return

    local commands="switch checkout-pr completion status push clean delete replay-list empty"
    local global_opts="-h --help"

    # Complete first argument (command)
    if [[ $cword -eq 1 ]]; then
        COMPREPLY=($(compgen -W "$commands" -- "$cur"))
        return 0
    fi

    # Get the command
    local cmd="${words[1]}"

    if [[ "$cmd" == "completion" && $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "fish bash zsh" -- "$cur"))
        return 0
    fi

    case "$cmd" in
        completion)
            COMPREPLY=($(compgen -W "-h --help" -- "$cur"))
            ;;
        status)
            COMPREPLY=($(compgen -W "-h --help" -- "$cur"))
            ;;
        checkout-pr)
            COMPREPLY=($(compgen -W "-h --help" -- "$cur"))
            ;;
        push)
            COMPREPLY=($(compgen -W "-h --help" -- "$cur"))
            ;;
        switch)
            COMPREPLY=($(compgen -W "-h --help" -- "$cur"))
            ;;
        clean)
            COMPREPLY=($(compgen -W "--changes --untracked --ignored --all --yes -y -h --help" -- "$cur"))
            ;;
        delete)
            COMPREPLY=($(compgen -W "-h --help" -- "$cur"))
            ;;
        replay-list)
            COMPREPLY=($(compgen -W "-h --help" -- "$cur"))
            ;;
        empty)
            COMPREPLY=($(compgen -W "-h --help" -- "$cur"))
            ;;
        *)
            COMPREPLY=($(compgen -W "$global_opts" -- "$cur"))
            ;;
    esac

    return 0
}

complete -F _gitgum_completion __GITGUM_CMD__
`,
	"fish": `# Fish completion for gitgum (template - __GITGUM_CMD__ will be replaced)

function __fish_gitgum_needs_command
    set -l cmd (commandline -opc)
    test (count $cmd) -eq 1
end

function __fish_gitgum_using_command
    set -l cmd (commandline -opc)
    test (count $cmd) -gt 1; and contains -- $cmd[2] $argv
end

# Main commands
complete -f -c __GITGUM_CMD__ -n __fish_gitgum_needs_command -a switch -d "Switch to a branch interactively"
complete -f -c __GITGUM_CMD__ -n __fish_gitgum_needs_command -a checkout-pr -d "Checkout a pull request from a remote repository"
complete -f -c __GITGUM_CMD__ -n __fish_gitgum_needs_command -a completion -d "Output shell completion script"
complete -f -c __GITGUM_CMD__ -n __fish_gitgum_needs_command -a status -d "Show the status of the current git repository"
complete -f -c __GITGUM_CMD__ -n __fish_gitgum_needs_command -a push -d "Push the current branch to a remote repository"
complete -f -c __GITGUM_CMD__ -n __fish_gitgum_needs_command -a clean -d "Discard working tree changes and untracked files"
complete -f -c __GITGUM_CMD__ -n __fish_gitgum_needs_command -a delete -d "Delete a local branch and optionally its remote tracking branch"
complete -f -c __GITGUM_CMD__ -n __fish_gitgum_needs_command -a replay-list -d "List commits on branch A since divergence from trunk B"
complete -f -c __GITGUM_CMD__ -n __fish_gitgum_needs_command -a empty -d "Create an empty commit and optionally push it"

# Global options
complete -f -c __GITGUM_CMD__ -s h -l help -d "Show help message"

# Completion command - suggest shell types
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command completion' -a "fish bash zsh" -d "Shell type"
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command completion' -s h -l help -d "Show help for completion"

# Status command - help option
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command status' -s h -l help -d "Show help for status"

# Checkout-PR command - help option
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command checkout-pr' -s h -l help -d "Show help for checkout-pr"

# Push command - help option
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command push' -s h -l help -d "Show help for push"

# Switch command - help option
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command switch' -s h -l help -d "Show help for switch"

# Clean command - flags and options
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command clean' -l changes -d "Discard staged and unstaged changes (default: true)"
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command clean' -l untracked -d "Remove untracked files (default: true)"
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command clean' -l ignored -d "Remove ignored files (default: false)"
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command clean' -l all -d "Enable all cleanup options"
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command clean' -l yes -d "Skip confirmation prompt"
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command clean' -s y -d "Skip confirmation prompt (short)"
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command clean' -s h -l help -d "Show help for clean"

# Delete command - help option
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command delete' -s h -l help -d "Show help for delete"

# Replay-list command - help option
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command replay-list' -s h -l help -d "Show help for replay-list"

# Empty command - help option
complete -f -c __GITGUM_CMD__ -n '__fish_gitgum_using_command empty' -s h -l help -d "Show help for empty"
`,
	"zsh": `#compdef __GITGUM_CMD__

# Zsh completion for gitgum (template - __GITGUM_CMD__ will be replaced)

_gitgum() {
    local -a commands

    commands=(
        'switch:Switch to a branch interactively'
        'checkout-pr:Checkout a pull request from a remote repository'
        'completion:Output shell completion script'
        'status:Show the status of the current git repository'
        'push:Push the current branch to a remote repository'
        'clean:Discard working tree changes and untracked files'
        'delete:Delete a local branch and optionally its remote tracking branch'
        'replay-list:List commits on branch A since divergence from trunk B'
        'empty:Create an empty commit and optionally push it'
    )

    local -a global_opts
    global_opts=(
        '-h[Show help message]'
        '--help[Show help message]'
    )

    if (( CURRENT == 2 )); then
        _describe 'command' commands
        return
    fi

    local cmd="${words[2]}"

    case "$cmd" in
        completion)
            if (( CURRENT == 3 )); then
                local -a shells
                shells=('fish' 'bash' 'zsh')
                _describe 'shell' shells
            else
                _arguments \
                    '-h[Show help message]' \
                    '--help[Show help message]'
            fi
            ;;
        status)
            _arguments \
                '-h[Show help message]' \
                '--help[Show help message]'
            ;;
        switch)
            _arguments \
                '-h[Show help message]' \
                '--help[Show help message]'
            ;;
        checkout-pr)
            _arguments \
                '-h[Show help message]' \
                '--help[Show help message]'
            ;;
        push)
            _arguments \
                '-h[Show help message]' \
                '--help[Show help message]'
            ;;
        clean)
            _arguments \
                '--changes[Discard staged and unstaged changes (default)]' \
                '--untracked[Remove untracked files (default)]' \
                '--ignored[Remove ignored files]' \
                '--all[Enable all cleanup options]' \
                '--yes[Skip confirmation prompt]' \
                '-y[Skip confirmation prompt]' \
                '-h[Show help message]' \
                '--help[Show help message]'
            ;;
        delete)
            _arguments \
                '-h[Show help message]' \
                '--help[Show help message]'
            ;;
        replay-list)
            _arguments \
                '-h[Show help message]' \
                '--help[Show help message]'
            ;;
        empty)
            _arguments \
                '-h[Show help message]' \
                '--help[Show help message]'
            ;;
        *)
            _arguments $global_opts
            ;;
    esac
}

_gitgum "$@"

`,
}
